{
	"error": {
		"iotaAttestationConnector": {
			"inclusionFailed": "The transaction generated for the attestation was not included in a reasonable amount of time",
			"attestingFailed": "Attesting the data failed",
			"verificationFailed": "Verifying the attestation failed",
			"transferFailed": "Transferring the attestation failed",
			"namespaceMismatch": "The namespace in the urn \"{id}\" does not match the namespace of the IOTA Attestation connector \"{namespace}\""
		}
	},
	"iotaAttestationConnector": {
		"verificationFailures": {
			"noData": "There is no data in the resolved NFT",
			"proofFailed": "The proof of the attestation could not be verified",
			"revoked": "The proof of the attestation has been revoked"
		}
	}
}
